Afya/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from Afya import views


app_name = 'Afya'

urlpatterns = [
                  path('', views.index, name="index"),
                  path('login/', views.user_login, name='login'),
                  path('register/', views.user_register, name='register'),
                  path('logout/', views.user_logout, name='logout'),
                  path('about/', views.about, name="about"),
                  path('contact/', views.contact, name="contact"),
                  path('cart/', views.view_cart, name='view_cart'),
                  path('phamarcy/', views.pharmacy, name="pharmacy"),
                  path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
                  path('make_payment/', views.make_payment, name='make_payment'),
                  path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),

                  path('doctor_profile/<int:doctor_id>/', views.doctor_profile, name='doctor_profile'),
                  path('reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AfyaYangu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Afya.urls')),
]

Afya/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import FileExtensionValidator
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='media/product', default='media/adverts/background.jpg')
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def total_price(self):
        return self.product.price * self.quantity


class Payment(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    transaction_id = models.CharField(max_length=255, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)


class DoctorCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.ForeignKey(DoctorCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='media/Doctor', default='media/Doctor/female-doctor.jpg',
                              validators=[FileExtensionValidator(['jpg', 'jpeg', 'png'])])
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('doctor_profile', kwargs={'doctor_id': self.id})

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_doctor_reply = models.BooleanField(default=False)
    doctor_reply = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"From {self.sender} to {self.recipient} on {self.timestamp}"


class Advert(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='media/adverts', default='media/adverts/background.jpg')
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.title

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Afya Yangu</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Free HTML5 Website Template by uicookies.com" />
  <meta name="keywords" content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
  <meta name="author" content="uicookies.com" />
  
  <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark probootstrap-navbar-dark">
    <div class="container">
      <!-- <a class="navbar-brand" href="index.html">Health</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-nav" aria-controls="probootstrap-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="probootstrap-nav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="/" class="nav-link pl-0">Home</a></li>
          <li class="nav-item"><a href="{% url 'Afya:pharmacy' %}" class="nav-link">Pharmacy</a></li>
          <li class="nav-item active"><a href="{% url 'Afya:about' %}" class="nav-link">About</a></li>
          <li class="nav-item"><a href="{% url 'Afya:contact' %}" class="nav-link">Contact</a></li>
        </ul>
        <div class="ml-auto">
          <form action="#" method="get" class="probootstrap-search-form mb-sm-0 mb-3">
            <div class="form-group">
              <button class="icon submit"><span class="icon-magnifying-glass"></span></button>
              <input type="text" class="form-control" placeholder="Search">
            </div>
          </form>
        </div>
      </div>
    </div>
  </nav>
  <!-- END nav -->
  <header role="banner" class="probootstrap-header py-5">
    <div class="container">
      <div class="row">
        <div >
          <a href="index.html" class="mr-auto">
              <img class="logo" src="{% static '/images/Screenshot__30_-removebg-preview.png' %}"
                                                    width="250" height="60" class="hires" alt="Afya Yangu"></a>
        </div>
        <div class="col-md-9">
          <div class="float-md-right float-none">
          <div class="probootstrap-contact-phone d-flex align-items-top mb-3 float-left">
            <span class="icon mr-2 Yangu-text"><i class=" Yangu-text icon-phone"></i></span>
            <span class="probootstrap-text Yangu-text"> +254794675478 <small class="d-block">
                <a href="#" class="arrow-link">Appointment <i class="icon-chevron-right"></i></a></small></span>
          </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="mb-5 float_shadow">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mb-5">
          <h1 class="display-4">About Us</h1>
          <p class="lead text-secondary">We are a Kenyan-owned online Pharmacy provide convenient
              access to medications and healthcare products, especially for individuals who may
              have difficulty visiting physical pharmacies, such as the elderly, disabled, or
              those in remote areas. We offer a high level of privacy and discretion for individuals
              who prefer not to discuss their medical conditions openly in a physical pharmacy.
              Beyond medication, we offer a range of health and wellness products, supplements,
              and services, catering to holistic well-being.</p>
        </div>
      </div>
    </div>
  </section>
  
  

  <section class="probootstrap-services float_shadow">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside">
          <div class="mb-3 pt-5">
            <h2 class="h6">About</h2>
            <ul class="list-unstyled probootstrap-light mb-4">
              <li class="active"><a href="#">What's Up?</a></li>
              <li><a href="#">Staffs</a></li>
{#              <li><a href="#">Career</a></li>#}
            </ul>
          </div>
        </div>
        <div class="col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside">
          <h1 class="mt-4 mb-4">What's Up?</h1>
          <p>Telemedicine is only occasionally used to offer patients direct healthcare services.
              Regularly employed when used with in-person clinical services, telemedicine enables
              the continuation of clinical services outside of the actual hospital infrastructure.</p>

         
          <p>The Kenya telehealth market is predicted to experience double-digit growth in the
              coming years as a result of rising healthcare costs, an increase in technological
              advancements in the healthcare industry, and efforts to find a solution to the
              accessibility issues of the healthcare sector in remote areas that have affected
              developing economies worldwide for years.</p>

         
        </div>
      </div>
    </div>
  </section>
  

 
<section class="probootstrap-subscribe">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-12">
        <h2 class="h1 text-white">Subscribe Newsletter</h2>
        <p class="lead text-white">"Compassionate Care, Exceptional Results."</p>
      </div>
    </div>
    <form action="#" method="post">
      <div class="row">
        <div class="col-md-4">
          <input type="text" class="form-control" placeholder="Name">    
        </div>
        <div class="col-md-4 mb-md-0 mb-3">
          <input type="text" class="form-control" placeholder="Email">
        </div>
        <div class="col-md-4">
          <input type="submit" value="Subscribe" class="btn btn-primary btn-block">
        </div>
      
      </div>
    </form>
  </div>
</section>  
  <footer class="probootstrap-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-3">
          <h3 class="heading">Latest Blog</h3>
          <ul class="list-unstyled probootstrap-footer-recent-post">
            <li>
              <a href="#"><span class="date">October 1, 2023</span> Preventive Care: Prevention
                  is often said to be the best medicine, and medical services excel in this area.
                  Routine check-ups, vaccinations, and health screenings are essential components
                  of preventive care. They detect potential health issues early, allowing for
                  timely intervention. </a>
            </li>
            <li>
              <a href="#"><span class="date">October 1, 2023</span>This month's question:
                  "How can I maintain a healthy work-life balance?" </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Head Office</h3>
          <p class="mb-5">Magadi road, Muungano Sacco Building,Ongata Rongai</p>
          <h3 class="heading text-white">Open</h3> 
          <p>
            Mon-Fri 7:30-18:00 <br>
            Sat 7:30-18:00 <br>
            Sun 7:30-18:00
          </p>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Quick Links</h3>
          <ul class="list-unstyled probootstrap-footer-links">
            <li><a href="#">Home</a></li>
            <li><a href="#">Pharmacy</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Follow us</h3>
          <ul class="probootstrap-footer-social">
            <li><a href="#"><span class="icon-twitter"></span></a></li>
            <li><a href="#"><span class="icon-facebook"></span></a></li>
            <li><a href="#"><span class="icon-linkedin"></span></a></li>
          </ul>
        </div>
      </div>
      <!-- END row -->
      <div class="row probootstrap-copyright">
        <div class="col-md-12">
          <p><small>&copy; 2023 <a href="https://uicookies.com/" target="_blank">Afya Yangu Health</a>. All Rights Reserved.</div>
        </div>
      </div>
    </div>
  </footer>

  <!-- loader -->
    <div id="probootstrap-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#32609e"/></svg></div>
  
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>
  
</body>
</html>

templates/cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<body>
    <h1 class="title">{{ request.user.username }}'s Cart</h1>
    <section>
    <div class="items">
  {% if cart_items %}
    <ul class="cart-items-list">
        {% for item in cart_items %}
            <div class="cart-item">
                <img alt="{{ item.product.name }} image" src="{{ item.product.image.url }}">
                <p>{{ item.product.name }}</p>
                <p> Quantity: {{ item.quantity }}</p>
                <p> Price: ${{ item.total_price }}</p>
                <a href="{% url 'Afya:remove_from_cart' product_id=item.product.id %}">Remove</a>
            </div>
        {% endfor %}
    </ul>
    <p class="total-price">Total Price: ${{ total_price }}</p>

    <form method="post" action="{% url 'Afya:make_payment' %}">
        {% csrf_token %}
        <button class="payment-button" type="submit">Make Payment</button>
    </form>
{% else %}
    <p class="empty-cart-message">Your cart is empty.</p>
    <p class="empty-cart-message"><a href="{% url 'Afya:pharmacy' %}">Browse all products</a></p>
{% endif %}

    </div>
    </section>
    <div class="user-info">
     <p  style="font-weight: bold;">Username: {{ request.user.username }}</p>
    <p  style="font-weight: bold;">Email: {{ request.user.email }}</p>
                    <a href="{% url 'Afya:index' %}">Home</a>
    </div>

</body>
</html>

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Afya Yangu</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Free HTML5 Website Template by uicookies.com" />
  <meta name="keywords" content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
  <meta name="author" content="uicookies.com" />
  
  <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">

 <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-blue probootstrap-navbar-dark">
    <div class="container">
      <!-- <a class="navbar-brand" href="index.html">Health</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-nav" aria-controls="probootstrap-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="probootstrap-nav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="/" class="nav-link pl-0">Home</a></li>
          <li class="nav-item"><a href="{% url 'Afya:pharmacy' %}" class="nav-link">Pharmacy</a></li>
          <li class="nav-item"><a href="{% url 'Afya:about' %}" class="nav-link">About</a></li>
          <li class="nav-item active"><a href="{% url 'Afya:contact' %}" class="nav-link">Contact</a></li>
        </ul>
        <div class="ml-auto">
          <form action="#" method="get" class="probootstrap-search-form mb-sm-0 mb-3">
            <div class="form-group">
              <button class="icon submit"><span class="icon-magnifying-glass"></span></button>
              <input type="text" class="form-control" placeholder="Search">
            </div>
          </form>
        </div>
      </div>
    </div>
  </nav>
  <!-- END nav -->
  <header role="banner" class="probootstrap-header py-5">
    <div class="container">
      <div class="row">
        <div>
          <a href="index.html" class="mr-auto"><img class="logo" src="{% static 'images/Screenshot__30_-removebg-preview.png' %}" width="212" height="48" class="hires" ></a>
        </div>  
        <div class="col-md-9">
          <div class="float-md-right float-none">
          <div class="probootstrap-contact-phone d-flex align-items-top mb-3 float-left">
            <span class="icon mr-2"><i class="icon-phone"></i></span>
            <span class="probootstrap-text Yangu-text"> +254794675478 <small class="d-block"><a href="#" class="arrow-link Yangu-text">Appointment <i class="icon-chevron-right"></i></a></small></span>
          </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="mb-5 float_shadow">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mb-5">
          <h1 class="display-4">Contact Us</h1>
          <p class="lead text-secondary">"Each day is an opportunity for a fresh start. We'll continue to work toward your recovery."</p>
        </div>
      </div>
    </div>
  </section>
  

  <section class="probootstrap-services float_shadow">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside">
          <div class="mb-3 pt-5">
            <h2 class="h6">Contact</h2>
            <ul class="list-unstyled probootstrap-light mb-4">
              <li class="active"><a href="#">Contact</a></li>
              <li><a href="#">More Link</a></li>
              <li><a href="#">Another Link</a></li>
            </ul>
          </div>
        </div>
        <div class=" col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside">
          <h1 class="mt-4 mb-4">Get In Touch</h1>
          <div class="row">
            <div class="col-md-12">
              <form action="" method="post" class="probootstrap-form">
                <div class="form-group">
                  <label for="name" class="sr-only">Name</label>
                  <input type="text" class="form-control" id="name" placeholder="Enter your name">
                </div>
                <div class="form-group">
                  <label for="email" class="sr-only">Email</label>
                  <input type="text" class="form-control" id="email" placeholder="Enter your email">
                </div>
                <div class="form-group">
                  <label for="message" class="sr-only">Message</label>
                  <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Write your message"></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-primary" value="Send Message">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  

  <section class="probootstrap-subscribe">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-12">
          <h2 class="h1 text-white">Subscribe Newsletter</h2>
          <p class="lead text-white">"Compassionate Care, Exceptional Results."</p>
        </div>
      </div>
      <form action="#" method="post">
        <div class="row">
          <div class="col-md-4">
            <input type="text" class="form-control" placeholder="Name">    
          </div>
          <div class="col-md-4 mb-md-0 mb-3">
            <input type="text" class="form-control" placeholder="Email">
          </div>
          <div class="col-md-4">
            <input type="submit" value="Subscribe" class="btn btn-primary btn-block">
          </div>
        
        </div>
      </form>
    </div>
  </section>  

  <footer class="probootstrap-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-3">
          <h3 class="heading">Latest Blog</h3>
          <ul class="list-unstyled probootstrap-footer-recent-post">
            <li>
              <a href="#"><span class="date">October 1, 2023</span> Preventive Care: Prevention is often said to be the
                  best medicine, and medical services excel in this area. Routine check-ups, vaccinations, and
                  health screenings are essential components of preventive care. They detect potential health
                  issues early, allowing for timely intervention. </a>
            </li>
            <li>
              <a href="#"><span class="date">October 1, 2023</span>This month's question: "How can I maintain a healthy work-life balance?" </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Head Office</h3>
          <p class="mb-5">Magadi road, Muungano Sacco Building,Ongata Rongai</p>
          <h3 class="heading text-white">Open</h3> 
          <p>
            Mon-Fri 7:30-18:00 <br>
            Sat 7:30-18:00 <br>
            Sun 7:30-18:00
          </p>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Quick Links</h3>
          <ul class="list-unstyled probootstrap-footer-links">
            <li><a href="#">Home</a></li>
            <li><a href="#">Department</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h3 class="heading">Follow us</h3>
          <ul class="probootstrap-footer-social">
            <li><a href="#"><span class="icon-twitter"></span></a></li>
            <li><a href="#"><span class="icon-facebook"></span></a></li>
            <li><a href="#"><span class="icon-linkedin"></span></a></li>
          </ul>
        </div>
      </div>
      <!-- END row -->
      <div class="row Afya Yangu-copyright">
        <div class="col-md-12">
          <p><small>&copy; 2023 <a href="https://uicookies.com/" target="_blank">Afya Yangu Health</a>. All Rights Reserved.</div>
      </div>
    </div>
  </footer>

  <!-- loader
   -->
    <div id="Afya Yangu-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#32609e"/></svg></div>
  

  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>
  
</body>
</html>

templates/doctor_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ doctor.name }}'s Profile</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
</head>
<body>
<nav class="navbar">
    <ul>
        <li class="home"><a href="{% url 'Afya:index' %}">Home</a></li> <!-- Add this line for the home link -->
        <!-- Add other navbar links as needed -->
        <!-- For example, you might have links for Products, Doctors, Users, etc. -->
    </ul>
</nav>
<!-- Display doctor information -->
<div id="doctor-profile" class="container">
    <h2>{{ doctor.name }}'s Profile</h2>
    <img src="{{ doctor.image.url }}" alt="{{ doctor.name }}" width="200">
    <p>{{ doctor.description }}</p>
</div>

<!-- Display user messages -->
<div id="user-messages" class="container">
    <h2>User Messages</h2>
    <ul>
        {% for message in messages %}
            {% if message.sender.username == user.username %}
                <li>
                    <strong>{{ message.sender.username }}</strong>:
                    {% if message.is_doctor_reply and message.doctor_reply %}
                        (Doctor's Reply): {{ message.doctor_reply }}
                    {% else %}
                        {{ message.content }}
                    {% endif %}
                    {% if is_doctor and request.user == doctor.user %}
                        <br>
                        <a href="#" class="reply-link" data-message-id="{{ message.id }}">Reply</a>
                        <div id="reply-form-container-{{ message.id }}" class="reply-form">
                            <!-- Reply form content loaded dynamically by JavaScript -->
                        </div>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

<!-- Form for sending messages -->
<div class="form-group">
{#{% if is_doctor and request.user == doctor.user %}#}
    <form method="post" action="{% url 'Afya:doctor_profile' doctor_id=doctor.id %}">
        {% csrf_token %}
        <label for="content">Send Message:</label>
        <textarea placeholder="Enter Message Here" name="content" rows="4" cols="50"></textarea>
        <br>
        <input type="submit" value="Send Message">
    </form>
{#{% else %}#}
{#    <p>Only doctors can send messages.</p>#}
{#{% endif %}#}
</div>
<!-- AJAX script -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $(".reply-link").on("click", function(event) {
            event.preventDefault();
            var messageId = $(this).data("message-id");
            var replyFormContainer = $("#reply-form-container-" + messageId);

            // Ensure that messageId is valid before making the AJAX request
            if (messageId) {
                // Load the reply form using AJAX
                $.get("{% url 'Afya:reply_message' 999 %}".replace('999', messageId), function(data) {
                    replyFormContainer.html(data);
                    replyFormContainer.slideToggle();
                });
            }
        });
    });
</script>
<script src="{% static 'js/dashboard.js' %}"></script>
<div class="footer">
    <p>&copy; 2023 Doctor Dashboard</p>
</div>
</body>
</html>